apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::838308125280:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-TCLEFMZYP3ML
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::838308125280:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-19T12:29:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "849"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: da7d8337-dc5c-477f-93b9-70e532461a5c
