apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::838308125280:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-NQGS4DKF33QQ
      username: system:node:{{EC2PrivateDNSName}}
      - rolearn: arn:aws:iam::838308125280:role/UdacityFlaskDeployCBKubectlRole
       username: build
       groups:
         - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-31T17:07:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "849"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 08afb5ac-3e77-405c-bf28-0d4de55aaaaf
